### ISSUE TITLE
Error around izoneapi dependency hosted on github

### ISSUE THREAD

**Issue by gondalez** [bluephlame/homebridge-izone3-aircon-platform#2]
Hi,

Thanks for your work :)
Would you consider publishing the `izoneapi` dependency to npm and re-linking in your [package.json](https://github.com/bluephlame/homebridge-izone3-aircon-platform/blob/master/package.json#L22)? 🙏 

I get a permissions error when trying to install on a vanilla version of homebridge within docker on a synology nas:

![image](https://user-images.githubusercontent.com/1468141/71775419-b3ca7080-2fbb-11ea-9244-5a7d75ade1b3.png)

**Comment by awynbergen** [comment]
Hi there I also getting problem installing in:
![image](https://user-images.githubusercontent.com/24240954/72658901-6524c980-39f2-11ea-99f5-01a49edd30b3.png)


Would so love to get my iZone working via homebridge. IFTTT is a pain !
